### ISSUE TITLE
Test against 3 latest releases of mypy + hard pin in plugin hook na latest

### ISSUE THREAD

**Issue by kornicameister** [kornicameister/loguru-mypy#47]
]Ref: #43 

- [x] run CI with several `mypy` versions [ #59 ]
- [x] pin the version (lowest) in plugin configuration [ #60 ]
- [x] update the documentation [ #61 ]

**Comment by ThibaultLemaire** [comment]
> This PR is a first PR to start tracking `mypy` version. No idea how low would you like to go, but if you have a suggestion to test even lower `mypy` version, let me know in the issue.

Good job on the PR! I was only thinking others might have higher expectations, personally I don't need anything below what I used for my PR (`mypy==0.782`) so it's already more than enough :)

If someone needs a lower version of mypy, they can always open an issue
